/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* HEATTIMER_QUERY_MATRIX_GENERATION ( int ) */
#if defined STAP_SDT_V1
#define HEATTIMER_QUERY_MATRIX_GENERATION_ENABLED() __builtin_expect (query__matrix_generation_semaphore, 0)
#define heattimer_query__matrix_generation_semaphore query__matrix_generation_semaphore
#else
#define HEATTIMER_QUERY_MATRIX_GENERATION_ENABLED() __builtin_expect (heattimer_query__matrix_generation_semaphore, 0)
#endif
__extension__ extern unsigned short heattimer_query__matrix_generation_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEATTIMER_QUERY_MATRIX_GENERATION(arg1) \
DTRACE_PROBE1 (heattimer, query__matrix_generation, arg1)

/* HEATTIMER_QUERY_START_CALC ( ) */
#if defined STAP_SDT_V1
#define HEATTIMER_QUERY_START_CALC_ENABLED() __builtin_expect (query__start_calc_semaphore, 0)
#define heattimer_query__start_calc_semaphore query__start_calc_semaphore
#else
#define HEATTIMER_QUERY_START_CALC_ENABLED() __builtin_expect (heattimer_query__start_calc_semaphore, 0)
#endif
__extension__ extern unsigned short heattimer_query__start_calc_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEATTIMER_QUERY_START_CALC() \
DTRACE_PROBE (heattimer, query__start_calc)

/* HEATTIMER_QUERY_START_ITERATION ( ) */
#if defined STAP_SDT_V1
#define HEATTIMER_QUERY_START_ITERATION_ENABLED() __builtin_expect (query__start_iteration_semaphore, 0)
#define heattimer_query__start_iteration_semaphore query__start_iteration_semaphore
#else
#define HEATTIMER_QUERY_START_ITERATION_ENABLED() __builtin_expect (heattimer_query__start_iteration_semaphore, 0)
#endif
__extension__ extern unsigned short heattimer_query__start_iteration_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEATTIMER_QUERY_START_ITERATION() \
DTRACE_PROBE (heattimer, query__start_iteration)

/* HEATTIMER_QUERY_START_COPY ( ) */
#if defined STAP_SDT_V1
#define HEATTIMER_QUERY_START_COPY_ENABLED() __builtin_expect (query__start_copy_semaphore, 0)
#define heattimer_query__start_copy_semaphore query__start_copy_semaphore
#else
#define HEATTIMER_QUERY_START_COPY_ENABLED() __builtin_expect (heattimer_query__start_copy_semaphore, 0)
#endif
__extension__ extern unsigned short heattimer_query__start_copy_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEATTIMER_QUERY_START_COPY() \
DTRACE_PROBE (heattimer, query__start_copy)

/* HEATTIMER_QUERY_END_ITERATION ( int ) */
#if defined STAP_SDT_V1
#define HEATTIMER_QUERY_END_ITERATION_ENABLED() __builtin_expect (query__end_iteration_semaphore, 0)
#define heattimer_query__end_iteration_semaphore query__end_iteration_semaphore
#else
#define HEATTIMER_QUERY_END_ITERATION_ENABLED() __builtin_expect (heattimer_query__end_iteration_semaphore, 0)
#endif
__extension__ extern unsigned short heattimer_query__end_iteration_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEATTIMER_QUERY_END_ITERATION(arg1) \
DTRACE_PROBE1 (heattimer, query__end_iteration, arg1)

/* HEATTIMER_QUERY_END_CALC ( ) */
#if defined STAP_SDT_V1
#define HEATTIMER_QUERY_END_CALC_ENABLED() __builtin_expect (query__end_calc_semaphore, 0)
#define heattimer_query__end_calc_semaphore query__end_calc_semaphore
#else
#define HEATTIMER_QUERY_END_CALC_ENABLED() __builtin_expect (heattimer_query__end_calc_semaphore, 0)
#endif
__extension__ extern unsigned short heattimer_query__end_calc_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define HEATTIMER_QUERY_END_CALC() \
DTRACE_PROBE (heattimer, query__end_calc)

